name: Run Spotify Data Script

on:
  schedule:
    - cron: '30 21 * * *' # Runs daily at midnight CET
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Spotify Data Script
        run: python Unlimited_Spotify_Wrapped.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
